### ISSUE TITLE
compile

### ISSUE THREAD

**Issue by tinaayam** [ZeroM3m0ry/Orca#2]
hi there how could i compile this program.
I don't have knowledge in c++ so I am not being able tocompile.
I am using g++ orca.cp command to compile but gave an error.

**Comment by ZeroM3m0ry** [comment]
can you provide me more detail about the error , the program was written in [ visual studio](https://visualstudio.microsoft.com/vs/)
IDE its work fine in it  so you may need to download it , in other compilers you will probably  face some  issues in header files .

**Comment by ZeroM3m0ry** [comment]
@tinaayam you can test  the executable version by downloading it from here [Orca ](https://github.com/ZeroM3m0ry/Orca/releases/tag/Orca) enjoy .
