### ISSUE TITLE
application error

### ISSUE THREAD

**Issue by tinaayam** [ZeroM3m0ry/Orca#3]
hi there, I downloaded the exe provided in thereleases.
It gave various errors which I fixed by installing the required packages.
but still it is giving an error when I am trying to launch orca.
here is the error.
Orca.exe - Application Error  dialog  The application was unable to start correctly (0xc000007b). Click OK to close the application. 
what are the possible ways to fix this error.
I have tried launching using administrator rights but still the problem is same.

**Comment by ZeroM3m0ry** [comment]
you have missing microsoft visual c++ packages download  [AiO Runtime ](https://all-in-one-runtimes.updatestar.com/en) Runtime it will set up all the needed packages .
